# This workflow will build the latest source files in Anaconda.

name: Tensorflow Compatibility Check

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.8']

    steps:
      - uses: actions/checkout@v2

      - name: common deps
        run: |
          pip install numpy matplotlib joblib tqdm
      
      - name: tf1
        if: ${{ matrix.python-version == '3.6' }}
        run: |
          pip install tensorflow==1.15.0
          python test_script.py
          
      - name: tf2
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          pip install tensorflow>=2
          python test_script.py
